php artisan optimize;
php artisan config:clear;
php artisan route:clear;
php artisan view:clear;
php artisan event:clear;
php artisan route:cache;
php artisan config:cache
php artisan cache:clear;
php artisan optimize:clear;
php artisan schedule:clear-cache;
